compatibility_date = "2022-02-06"
name = "worker-bompietro"
type = "javascript"
account_id = "4706a369fed984bbcf017f2ba89b1543"
workers_dev = true
route = "bompietro.com/*"
zone_id = "4647e6f62287ecaa74a78a34c20dac4f"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"
upload.format = "service-worker"
